/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { CommandProcessingResult } from '../model/commandProcessingResult';
// @ts-ignore
import { ExternalTransferLoanProductAttributesTemplateData } from '../model/externalTransferLoanProductAttributesTemplateData';
// @ts-ignore
import { PageExternalTransferLoanProductAttributesData } from '../model/pageExternalTransferLoanProductAttributesData';
// @ts-ignore
import { PostExternalAssetOwnerLoanProductAttributeRequest } from '../model/postExternalAssetOwnerLoanProductAttributeRequest';
// @ts-ignore
import { PutExternalAssetOwnerLoanProductAttributeRequest } from '../model/putExternalAssetOwnerLoanProductAttributeRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ExternalAssetOwnerLoanProductAttributesService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Retrieve All Loan Product Attributes
     * Retrieves all Loan Product Attributes with a given loanProductId
     * @endpoint get /v1/external-asset-owners/loan-product/{loanProductId}/attributes
     * @param loanProductId loanProductId
     * @param attributeKey attributeKey
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, attributeKey?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PageExternalTransferLoanProductAttributesData>;
    public getExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, attributeKey?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PageExternalTransferLoanProductAttributesData>>;
    public getExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, attributeKey?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PageExternalTransferLoanProductAttributesData>>;
    public getExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, attributeKey?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (loanProductId === null || loanProductId === undefined) {
            throw new Error('Required parameter loanProductId was null or undefined when calling getExternalAssetOwnersLoanProductLoanProductIdAttributes.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'attributeKey',
            <any>attributeKey,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        // authentication (basicAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('basicAuth', 'Authorization', localVarHeaders, 'Basic ');

        // authentication (tenantid) required
        localVarHeaders = this.configuration.addCredentialToHeaders('tenantid', 'fineract-platform-tenantid', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/external-asset-owners/loan-product/${this.configuration.encodeParam({name: "loanProductId", value: loanProductId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int64"})}/attributes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PageExternalTransferLoanProductAttributesData>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieve External Asset Owner Loan Product Attributes Template
     * Retrieves all available external asset owner loan product attributes and the values each attribute can take.
     * @endpoint get /v1/external-asset-owners/loan-product/template
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getExternalAssetOwnersLoanProductTemplate(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<ExternalTransferLoanProductAttributesTemplateData>>;
    public getExternalAssetOwnersLoanProductTemplate(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<ExternalTransferLoanProductAttributesTemplateData>>>;
    public getExternalAssetOwnersLoanProductTemplate(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<ExternalTransferLoanProductAttributesTemplateData>>>;
    public getExternalAssetOwnersLoanProductTemplate(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (basicAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('basicAuth', 'Authorization', localVarHeaders, 'Basic ');

        // authentication (tenantid) required
        localVarHeaders = this.configuration.addCredentialToHeaders('tenantid', 'fineract-platform-tenantid', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/external-asset-owners/loan-product/template`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<ExternalTransferLoanProductAttributesTemplateData>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create External Asset Owner Loan Product Attribute
     * @endpoint post /v1/external-asset-owners/loan-product/{loanProductId}/attributes
     * @param loanProductId loanProductId
     * @param postExternalAssetOwnerLoanProductAttributeRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public postExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, postExternalAssetOwnerLoanProductAttributeRequest: PostExternalAssetOwnerLoanProductAttributeRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CommandProcessingResult>;
    public postExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, postExternalAssetOwnerLoanProductAttributeRequest: PostExternalAssetOwnerLoanProductAttributeRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CommandProcessingResult>>;
    public postExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, postExternalAssetOwnerLoanProductAttributeRequest: PostExternalAssetOwnerLoanProductAttributeRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CommandProcessingResult>>;
    public postExternalAssetOwnersLoanProductLoanProductIdAttributes(loanProductId: number, postExternalAssetOwnerLoanProductAttributeRequest: PostExternalAssetOwnerLoanProductAttributeRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (loanProductId === null || loanProductId === undefined) {
            throw new Error('Required parameter loanProductId was null or undefined when calling postExternalAssetOwnersLoanProductLoanProductIdAttributes.');
        }
        if (postExternalAssetOwnerLoanProductAttributeRequest === null || postExternalAssetOwnerLoanProductAttributeRequest === undefined) {
            throw new Error('Required parameter postExternalAssetOwnerLoanProductAttributeRequest was null or undefined when calling postExternalAssetOwnersLoanProductLoanProductIdAttributes.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (basicAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('basicAuth', 'Authorization', localVarHeaders, 'Basic ');

        // authentication (tenantid) required
        localVarHeaders = this.configuration.addCredentialToHeaders('tenantid', 'fineract-platform-tenantid', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/external-asset-owners/loan-product/${this.configuration.encodeParam({name: "loanProductId", value: loanProductId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int64"})}/attributes`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CommandProcessingResult>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: postExternalAssetOwnerLoanProductAttributeRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a Loan Product Attribute
     * Updates a loan product attribute with a given loan product id and attribute id
     * @endpoint put /v1/external-asset-owners/loan-product/{loanProductId}/attributes/{id}
     * @param loanProductId loanProductId
     * @param id attributeId
     * @param putExternalAssetOwnerLoanProductAttributeRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public putExternalAssetOwnersLoanProductLoanProductIdAttributesId(loanProductId: number, id: number, putExternalAssetOwnerLoanProductAttributeRequest: PutExternalAssetOwnerLoanProductAttributeRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CommandProcessingResult>;
    public putExternalAssetOwnersLoanProductLoanProductIdAttributesId(loanProductId: number, id: number, putExternalAssetOwnerLoanProductAttributeRequest: PutExternalAssetOwnerLoanProductAttributeRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CommandProcessingResult>>;
    public putExternalAssetOwnersLoanProductLoanProductIdAttributesId(loanProductId: number, id: number, putExternalAssetOwnerLoanProductAttributeRequest: PutExternalAssetOwnerLoanProductAttributeRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CommandProcessingResult>>;
    public putExternalAssetOwnersLoanProductLoanProductIdAttributesId(loanProductId: number, id: number, putExternalAssetOwnerLoanProductAttributeRequest: PutExternalAssetOwnerLoanProductAttributeRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (loanProductId === null || loanProductId === undefined) {
            throw new Error('Required parameter loanProductId was null or undefined when calling putExternalAssetOwnersLoanProductLoanProductIdAttributesId.');
        }
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling putExternalAssetOwnersLoanProductLoanProductIdAttributesId.');
        }
        if (putExternalAssetOwnerLoanProductAttributeRequest === null || putExternalAssetOwnerLoanProductAttributeRequest === undefined) {
            throw new Error('Required parameter putExternalAssetOwnerLoanProductAttributeRequest was null or undefined when calling putExternalAssetOwnersLoanProductLoanProductIdAttributesId.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (basicAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('basicAuth', 'Authorization', localVarHeaders, 'Basic ');

        // authentication (tenantid) required
        localVarHeaders = this.configuration.addCredentialToHeaders('tenantid', 'fineract-platform-tenantid', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/external-asset-owners/loan-product/${this.configuration.encodeParam({name: "loanProductId", value: loanProductId, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int64"})}/attributes/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int64"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CommandProcessingResult>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: putExternalAssetOwnerLoanProductAttributeRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
