/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Office } from './office';
import { Group } from './group';
import { ClientIdentifier } from './clientIdentifier';
import { ExternalId } from './externalId';
import { Staff } from './staff';
import { CodeValue } from './codeValue';
import { AppUser } from './appUser';


export interface Client { 
    accountNumber?: string;
    activatedBy?: AppUser;
    activationDate?: string;
    active?: boolean;
    clientClassification?: CodeValue;
    clientType?: CodeValue;
    closed?: boolean;
    closedBy?: AppUser;
    closureDate?: string;
    closureReason?: CodeValue;
    createdBy: number;
    createdDate: string;
    dateOfBirth?: string;
    displayName?: string;
    emailAddress?: string;
    externalId?: ExternalId;
    firstname?: string;
    fullname?: string;
    gender?: CodeValue;
    groups?: Set<Group>;
    id?: number;
    identifiers?: Set<ClientIdentifier>;
    imageId?: number;
    lastModifiedBy: number;
    lastModifiedDate: string;
    lastname?: string;
    legalForm?: number;
    middlename?: string;
    mobileNo?: string;
    'new'?: boolean;
    notActive?: boolean;
    notPending?: boolean;
    office?: Office;
    officeJoiningDate?: string;
    pending?: boolean;
    proposedTransferDate?: string;
    reactivateDate?: string;
    reactivatedBy?: AppUser;
    rejected?: boolean;
    rejectedBy?: AppUser;
    rejectedDate?: string;
    rejectionDate?: string;
    rejectionReason?: CodeValue;
    reopenedBy?: AppUser;
    reopenedDate?: string;
    savingsAccountId?: number;
    savingsProductId?: number;
    staff?: Staff;
    status?: number;
    subStatus?: CodeValue;
    submittedOnDate?: string;
    transferInProgress?: boolean;
    transferInProgressOrOnHold?: boolean;
    transferOnHold?: boolean;
    transferToOffice?: Office;
    withdrawalDate?: string;
    withdrawalReason?: CodeValue;
    withdrawn?: boolean;
    withdrawnBy?: AppUser;
}

