/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SavingsAccountSummaryData } from './savingsAccountSummaryData';
import { CurrencyData } from './currencyData';
import { SavingsAccountStatusEnumData } from './savingsAccountStatusEnumData';
import { SavingsAccountChargeData } from './savingsAccountChargeData';
import { SavingsAccountApplicationTimelineData } from './savingsAccountApplicationTimelineData';
import { SavingsAccountTransactionData } from './savingsAccountTransactionData';
import { StaffData } from './staffData';
import { DepositProductData } from './depositProductData';
import { TaxGroupData } from './taxGroupData';
import { ChargeData } from './chargeData';
import { EnumOptionData } from './enumOptionData';


export interface DepositAccountData { 
    accountChart?: object;
    accountNo?: string;
    chargeOptions?: Array<ChargeData>;
    charges?: Array<SavingsAccountChargeData>;
    chartTemplate?: object;
    clientId?: number;
    clientName?: string;
    currency?: CurrencyData;
    depositProductId?: number;
    depositProductName?: string;
    depositType?: EnumOptionData;
    externalId?: string;
    fieldOfficerId?: number;
    fieldOfficerName?: string;
    fieldOfficerOptions?: Array<StaffData>;
    groupId?: number;
    groupName?: string;
    id?: number;
    interestCalculationDaysInYearType?: EnumOptionData;
    interestCalculationDaysInYearTypeOptions?: Array<EnumOptionData>;
    interestCalculationType?: EnumOptionData;
    interestCalculationTypeOptions?: Array<EnumOptionData>;
    interestCompoundingPeriodType?: EnumOptionData;
    interestCompoundingPeriodTypeOptions?: Array<EnumOptionData>;
    interestPostingPeriodType?: EnumOptionData;
    interestPostingPeriodTypeOptions?: Array<EnumOptionData>;
    lockinPeriodFrequency?: number;
    lockinPeriodFrequencyType?: EnumOptionData;
    lockinPeriodFrequencyTypeOptions?: Array<EnumOptionData>;
    minBalanceForInterestCalculation?: number;
    minRequiredOpeningBalance?: number;
    nominalAnnualInterestRate?: number;
    productId?: number;
    productOptions?: Array<DepositProductData>;
    status?: SavingsAccountStatusEnumData;
    summary?: SavingsAccountSummaryData;
    taxGroup?: TaxGroupData;
    timeline?: SavingsAccountApplicationTimelineData;
    transactions?: Array<SavingsAccountTransactionData>;
    withHoldTax?: boolean;
    withdrawalFeeForTransfers?: boolean;
    withdrawalFeeTypeOptions?: Array<EnumOptionData>;
}

