/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Working capital loan running balances
 */
export interface GetBalance { 
    /**
     * Cumulative breach past due amount, summed from each breach schedule period\'s outstanding amount
     */
    breachPastDueAmount?: number;
    fee?: number;
    feeOutstanding?: number;
    feePaid?: number;
    /**
     * Fees moved out of the outstanding balance by a write-off
     */
    feeWrittenOff?: number;
    id?: number;
    overpaymentAmount?: number;
    penalty?: number;
    penaltyOutstanding?: number;
    penaltyPaid?: number;
    /**
     * Penalties moved out of the outstanding balance by a write-off
     */
    penaltyWrittenOff?: number;
    /**
     * Total repayable principal: the disbursed amount plus the discount fee. Zero until disbursement, and zero again once a disbursal is undone.
     */
    principal?: number;
    principalAdjustment?: number;
    principalOutstanding?: number;
    principalPaid?: number;
    /**
     * Principal moved out of the outstanding balance by a write-off
     */
    principalWrittenOff?: number;
    realizedIncomeFromDiscountFee?: number;
    /**
     * Total amount actually disbursed
     */
    totalDisbursement?: number;
    totalDiscountFee?: number;
    totalDiscountFeeAdjustment?: number;
    totalExpectedRepayment?: number;
    totalOutstanding?: number;
    /**
     * Collected after the write-off and recognized as recovery income
     */
    totalRecovered?: number;
    totalRepayment?: number;
    /**
     * Gross amount written off; not reduced by recoveries
     */
    totalWrittenOff?: number;
    unrealizedIncomeFromDiscountFee?: number;
    /**
     * Still recoverable (totalWrittenOff - totalRecovered); caps the next recovery payment
     */
    writtenOffOutstanding?: number;
}

