/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetLoansLoanIdCollateralData } from './getLoansLoanIdCollateralData';
import { GetLoansLoanIdStatus } from './getLoansLoanIdStatus';
import { GetLoansLoanIdRepaymentFrequencyType } from './getLoansLoanIdRepaymentFrequencyType';
import { StringEnumOptionData } from './stringEnumOptionData';
import { GetLoansLoanIdLoanType } from './getLoansLoanIdLoanType';
import { GetLoansLoanIdTimeline } from './getLoansLoanIdTimeline';
import { DelinquencyRangeData } from './delinquencyRangeData';
import { GetLoansLoanIdAmortizationType } from './getLoansLoanIdAmortizationType';
import { GetLoansLoanIdTermPeriodFrequencyType } from './getLoansLoanIdTermPeriodFrequencyType';
import { GetLoansLoanIdCurrency } from './getLoansLoanIdCurrency';
import { EnumOptionData } from './enumOptionData';
import { GetLoansLoanIdDelinquencySummary } from './getLoansLoanIdDelinquencySummary';
import { GetLoansLoanIdOriginatorData } from './getLoansLoanIdOriginatorData';
import { GetLoansLoanIdTransactions } from './getLoansLoanIdTransactions';
import { GetLoansLoanIdLoanChargeData } from './getLoansLoanIdLoanChargeData';
import { GetLoansLoanIdSubStatus } from './getLoansLoanIdSubStatus';
import { GetLoansLoanIdDisbursementDetails } from './getLoansLoanIdDisbursementDetails';
import { GetLoansLoanIdInterestRateFrequencyType } from './getLoansLoanIdInterestRateFrequencyType';
import { GetLoansLoanIdInterestType } from './getLoansLoanIdInterestType';
import { GetLoansLoanIdRepaymentSchedule } from './getLoansLoanIdRepaymentSchedule';
import { GetLoansLoanIdSummary } from './getLoansLoanIdSummary';
import { GetLoansLoanIdLoanTermVariations } from './getLoansLoanIdLoanTermVariations';
import { GetLoansLoanIdInterestCalculationPeriodType } from './getLoansLoanIdInterestCalculationPeriodType';


/**
 * GetLoansLoanIdResponse
 */
export interface GetLoansLoanIdResponse { 
    accountNo?: string;
    actualNoTerm?: number;
    /**
     * Allow full term length for each tranche disbursement
     */
    allowFullTermForTranche?: boolean;
    amortizationType?: GetLoansLoanIdAmortizationType;
    annualInterestRate?: number;
    approvedPrincipal?: number;
    buyDownFeeCalculationType?: StringEnumOptionData;
    buyDownFeeIncomeType?: StringEnumOptionData;
    buyDownFeeStrategy?: StringEnumOptionData;
    capitalizedIncomeCalculationType?: StringEnumOptionData;
    capitalizedIncomeStrategy?: StringEnumOptionData;
    capitalizedIncomeType?: StringEnumOptionData;
    chargeOffBehaviour?: StringEnumOptionData;
    chargedOff?: boolean;
    /**
     * Set of charges
     */
    charges?: Array<GetLoansLoanIdLoanChargeData>;
    clientExternalId?: string;
    clientId?: number;
    clientName?: string;
    clientOfficeId?: number;
    collateral?: Array<GetLoansLoanIdCollateralData>;
    currency?: GetLoansLoanIdCurrency;
    delinquencyRange?: DelinquencyRangeData;
    delinquent?: GetLoansLoanIdDelinquencySummary;
    disallowExpectedDisbursements?: boolean;
    disbursedAmountPercentageForDownPayment?: number;
    /**
     * List of GetLoansLoanIdDisbursementDetails
     */
    disbursementDetails?: Array<GetLoansLoanIdDisbursementDetails>;
    /**
     * List of GetLoansLoanIdLoanTermVariations
     */
    emiAmountVariations?: Array<GetLoansLoanIdLoanTermVariations>;
    enableAutoRepaymentForDownPayment?: boolean;
    enableBuyDownFee?: boolean;
    enableDownPayment?: boolean;
    enableIncomeCapitalization?: boolean;
    enableInstallmentLevelDelinquency?: boolean;
    externalId?: string;
    fixedLength?: number;
    fixedPrincipalPercentagePerInstallment?: number;
    fraud?: boolean;
    graceOnArrearsAgeing?: number;
    graceOnInterestCharged?: number;
    graceOnInterestPayment?: number;
    graceOnPrincipalPayment?: number;
    id?: number;
    inArrearsTolerance?: number;
    interestCalculationPeriodType?: GetLoansLoanIdInterestCalculationPeriodType;
    interestRateFrequencyType?: GetLoansLoanIdInterestRateFrequencyType;
    interestRatePerPeriod?: number;
    interestRecognitionOnDisbursementDate?: boolean;
    interestType?: GetLoansLoanIdInterestType;
    isFloatingInterestRate?: boolean;
    lastClosedBusinessDate?: string;
    loanOfficerId?: number;
    loanOfficerName?: string;
    loanProductDescription?: string;
    loanProductId?: number;
    loanProductName?: string;
    loanPurposeId?: number;
    loanPurposeName?: string;
    loanScheduleProcessingType?: EnumOptionData;
    loanScheduleType?: EnumOptionData;
    /**
     * List of GetLoansLoanIdLoanTermVariations
     */
    loanTermVariations?: Array<GetLoansLoanIdLoanTermVariations>;
    loanType?: GetLoansLoanIdLoanType;
    netDisbursalAmount?: number;
    numberOfRepayments?: number;
    /**
     * List of originators associated with this loan
     */
    originators?: Array<GetLoansLoanIdOriginatorData>;
    overpaidOnDate?: string;
    principal?: number;
    proposedPrincipal?: number;
    repaymentEvery?: number;
    repaymentFrequencyType?: GetLoansLoanIdRepaymentFrequencyType;
    repaymentSchedule?: GetLoansLoanIdRepaymentSchedule;
    repaymentStartDateType?: EnumOptionData;
    status?: GetLoansLoanIdStatus;
    subStatus?: GetLoansLoanIdSubStatus;
    summary?: GetLoansLoanIdSummary;
    termFrequency?: number;
    termPeriodFrequencyType?: GetLoansLoanIdTermPeriodFrequencyType;
    timeline?: GetLoansLoanIdTimeline;
    totalOverpaid?: number;
    transactionProcessingStrategyCode?: string;
    /**
     * Set of GetLoansLoanIdTransactions
     */
    transactions?: Array<GetLoansLoanIdTransactions>;
}

