/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentTypeData } from './paymentTypeData';
import { StringEnumOptionData } from './stringEnumOptionData';
import { CurrencyData } from './currencyData';
import { CodeValueData } from './codeValueData';
import { WorkingCapitalNearBreachData } from './workingCapitalNearBreachData';
import { GetDelinquencyBucket } from './getDelinquencyBucket';
import { FundData } from './fundData';
import { ChargeData } from './chargeData';
import { EnumOptionData } from './enumOptionData';
import { WorkingCapitalBreachData } from './workingCapitalBreachData';


/**
 * GetWorkingCapitalLoanProductsTemplateResponse
 */
export interface GetWorkingCapitalLoanProductsTemplateResponse { 
    accountingMappingOptions?: { [key: string]: object; };
    accountingRuleOptions?: Array<StringEnumOptionData>;
    advancedPaymentAllocationTransactionTypes?: Array<EnumOptionData>;
    advancedPaymentAllocationTypes?: Array<StringEnumOptionData>;
    amortizationTypeOptions?: Array<StringEnumOptionData>;
    breachOptions?: Array<WorkingCapitalBreachData>;
    breachStartTypeOptions?: Array<StringEnumOptionData>;
    chargeOffReasonOptions?: Array<CodeValueData>;
    chargeOptions?: Array<ChargeData>;
    currencyOptions?: Array<CurrencyData>;
    delinquencyBucketOptions?: Array<GetDelinquencyBucket>;
    delinquencyMinimumPaymentTypeOptions?: Array<StringEnumOptionData>;
    delinquencyStartTypeOptions?: Array<StringEnumOptionData>;
    fundOptions?: Array<FundData>;
    nearBreachOptions?: Array<WorkingCapitalNearBreachData>;
    /**
     * Payment amount calculation strategies a product can be created with
     */
    paymentAmountCalculationStrategyOptions?: Array<StringEnumOptionData>;
    paymentTypeOptions?: Array<PaymentTypeData>;
    penaltyOptions?: Array<ChargeData>;
    periodFrequencyTypeOptions?: Array<StringEnumOptionData>;
    writeOffReasonOptions?: Array<CodeValueData>;
}

