/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetBalance } from './getBalance';
import { GetWorkingCapitalLoanProductsResponse } from './getWorkingCapitalLoanProductsResponse';
import { StringEnumOptionData } from './stringEnumOptionData';
import { GetWorkingCapitalLoanCharge } from './getWorkingCapitalLoanCharge';
import { CodeValueData } from './codeValueData';
import { GetWorkingCapitalLoanNearBreach } from './getWorkingCapitalLoanNearBreach';
import { GetWorkingCapitalLoansLoanIdStatus } from './getWorkingCapitalLoansLoanIdStatus';
import { GetWorkingCapitalLoansLoanIdTimeline } from './getWorkingCapitalLoansLoanIdTimeline';
import { GetDelinquencyBucket } from './getDelinquencyBucket';
import { WorkingCapitalLoanPeriodPaymentRateChangeData } from './workingCapitalLoanPeriodPaymentRateChangeData';
import { CurrencyData } from './currencyData';
import { GetWorkingCapitalLoansClient } from './getWorkingCapitalLoansClient';
import { GetWorkingCapitalLoansLoanIdOriginatorData } from './getWorkingCapitalLoansLoanIdOriginatorData';
import { GetDisbursementDetail } from './getDisbursementDetail';
import { WorkingCapitalCollection } from './workingCapitalCollection';
import { GetWorkingCapitalLoanSummary } from './getWorkingCapitalLoanSummary';
import { GetWorkingCapitalLoanBreach } from './getWorkingCapitalLoanBreach';
import { GetPaymentAllocation } from './getPaymentAllocation';


/**
 * GetWorkingCapitalLoansLoanIdResponse
 */
export interface GetWorkingCapitalLoansLoanIdResponse { 
    accountNo?: string;
    amortizationType?: StringEnumOptionData;
    /**
     * Approved discount fee set during loan approval
     */
    approvedDiscountFee?: number;
    /**
     * Principal granted at approval; zero before approval and after undoing it (deliberate Working Capital divergence from classic loans)
     */
    approvedPrincipal?: number;
    balance?: GetBalance;
    breach?: GetWorkingCapitalLoanBreach;
    /**
     * Number of days to shift the start of the first breach schedule period after disbursement
     */
    breachGraceDays?: number;
    /**
     * Start date of the loan\'s breach, i.e. the fromDate of the earliest breached breach schedule period (the breach grace days are already reflected in this date). Null when the loan is not in breach
     */
    breachStartDate?: string;
    breachStartType?: StringEnumOptionData;
    /**
     * Annualized EIR as a fraction (0.1691 = 16.91%): (1 + dailyEir)^npvDayCount − 1; null if schedule not yet generated. Note: periodPaymentRateHistory[].calculatedAnnualEir is a percentage
     */
    calculatedAnnualEir?: number;
    chargeOffReason?: CodeValueData;
    /**
     * Whether the loan is charged off (pure accounting tag; the loan stays active)
     */
    chargedOff?: boolean;
    /**
     * Date the loan was charged off
     */
    chargedOffOnDate?: string;
    /**
     * Charges associated with the loan
     */
    charges?: Array<GetWorkingCapitalLoanCharge>;
    client?: GetWorkingCapitalLoansClient;
    clientAccountNo?: string;
    clientExternalId?: string;
    clientId?: number;
    clientName?: string;
    clientOfficeId?: number;
    currency?: CurrencyData;
    /**
     * Periodic (daily) effective interest rate computed via RATE(); null if schedule not yet generated
     */
    dailyEir?: number;
    delinquencyBucket?: GetDelinquencyBucket;
    /**
     * Number of grace days before delinquency tracking starts
     */
    delinquencyGraceDays?: number;
    /**
     * Start date of the loan\'s delinquency, i.e. the fromDate of the earliest delinquent range schedule period shifted by delinquencyGraceDays. Null when the loan is not delinquent
     */
    delinquencyStartDate?: string;
    delinquencyStartType?: StringEnumOptionData;
    delinquent?: WorkingCapitalCollection;
    disbursementDetails?: Array<GetDisbursementDetail>;
    /**
     * Discount fee set during loan disbursement
     */
    discountFee?: number;
    /**
     * Installment-level delinquency flag (Term-compatible name). True when the loan has a delinquency bucket configured (Working Capital tracks delinquency at the period level); false otherwise
     */
    enableInstallmentLevelDelinquency?: boolean;
    externalId?: string;
    /**
     * Fraud flag. True when the loan has been marked as fraudulent
     */
    fraud?: boolean;
    fundId?: number;
    fundName?: string;
    id?: number;
    /**
     * Last closed business date (COB)
     */
    lastClosedBusinessDate?: string;
    /**
     * Loan cycle (sequential WC loan counter per client+product)
     */
    loanProductCounter?: number;
    loanProductDescription?: string;
    loanProductId?: number;
    loanProductName?: string;
    nearBreach?: GetWorkingCapitalLoanNearBreach;
    /**
     * Net disbursal amount from the amortization schedule; null if schedule not yet generated
     */
    netDisbursalAmount?: number;
    /**
     * NPV day count used by the amortization schedule
     */
    npvDayCount?: number;
    /**
     * Number of repayments (effectiveTotalTerm from the amortization schedule; for WC this is the loan term in days); null if schedule not yet generated
     */
    numberOfRepayments?: number;
    /**
     * List of originators associated with this loan
     */
    originators?: Array<GetWorkingCapitalLoansLoanIdOriginatorData>;
    /**
     * Date on which loan was overpaid otherwise null
     */
    overpaidOnDate?: string;
    paymentAllocation?: Array<GetPaymentAllocation>;
    paymentRate?: number;
    /**
     * Daily expected payment amount from the amortization schedule; null if schedule not yet generated
     */
    periodPaymentAmount?: number;
    /**
     * Period payment rate change history, most recently booked first - which for a backdated change is not the same as effective-date order. Each entry carries the annual EIR (as a percentage, e.g. 43.756245 - unlike the top-level calculatedAnnualEir, which is a fraction), daily payment amount and segment term the amortization schedule computed when that change was booked; those are null for changes booked before the snapshot was introduced
     */
    periodPaymentRateHistory?: Array<WorkingCapitalLoanPeriodPaymentRateChangeData>;
    /**
     * Active principal: the requested amount while the application is pending, the granted amount from approval, the actually disbursed amount from disbursement. Undoing approval or disbursal restores the previous stage\'s value. This is the contractual principal, not the outstanding balance - see summary.principalOutstanding for that.
     */
    principal?: number;
    product?: GetWorkingCapitalLoanProductsResponse;
    /**
     * Proposed discount fee at loan submission time
     */
    proposedDiscountFee?: number;
    /**
     * Principal requested at submission; never changes afterwards
     */
    proposedPrincipal?: number;
    repaymentEvery?: number;
    repaymentFrequencyType?: StringEnumOptionData;
    status?: GetWorkingCapitalLoansLoanIdStatus;
    summary?: GetWorkingCapitalLoanSummary;
    timeline?: GetWorkingCapitalLoansLoanIdTimeline;
    totalPaymentVolume?: number;
    writeOffReason?: CodeValueData;
    /**
     * Date the loan was written off. Cleared by an undo write-off
     */
    writtenOffOnDate?: string;
}

