/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Office } from './office';
import { GroupLevel } from './groupLevel';
import { Staff } from './staff';
import { StaffAssignmentHistory } from './staffAssignmentHistory';
import { CodeValue } from './codeValue';
import { GroupRole } from './groupRole';
import { AppUser } from './appUser';
import { Client } from './client';


export interface Group { 
    accountNumber?: string;
    activatedBy?: AppUser;
    activationDate?: string;
    active?: boolean;
    activeClientMembers?: Set<Client>;
    center?: boolean;
    childGroup?: boolean;
    clientMembers?: Set<Client>;
    closed?: boolean;
    closedBy?: AppUser;
    closureDate?: string;
    closureReason?: CodeValue;
    externalId?: string;
    group?: boolean;
    groupLevel?: GroupLevel;
    groupMembers?: Array<Group>;
    groupRole?: Set<GroupRole>;
    hierarchy?: string;
    id?: number;
    name?: string;
    'new'?: boolean;
    notActive?: boolean;
    notPending?: boolean;
    office?: Office;
    parent?: Group;
    pending?: boolean;
    staff?: Staff;
    staffHistory?: Set<StaffAssignmentHistory>;
    status?: number;
    submittedBy?: AppUser;
    submittedOnDate?: string;
    transferInProgress?: boolean;
    transferInProgressOrOnHold?: boolean;
    transferOnHold?: boolean;
}

