/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PostProductsMarketPricePeriods } from './postProductsMarketPricePeriods';
import { PostProductsChargesSelected } from './postProductsChargesSelected';


/**
 * PostProductsTypeRequest
 */
export interface PostProductsTypeRequest { 
    accountingRule?: number;
    allowDividendCalculationForInactiveClients?: boolean;
    chargesSelected?: Set<PostProductsChargesSelected>;
    currencyCode?: string;
    description?: string;
    digitsAfterDecimal?: number;
    inMultiplesOf?: number;
    /**
     * Required with accountingRule=2 (cash based)
     */
    incomeFromFeeAccountId?: number;
    locale?: string;
    lockinPeriodFrequency?: number;
    lockinPeriodFrequencyType?: number;
    marketPricePeriods?: Set<PostProductsMarketPricePeriods>;
    maximumShares?: number;
    minimumActivePeriodForDividends?: number;
    minimumShares?: number;
    minimumactiveperiodFrequencyType?: number;
    name?: string;
    nominalShares?: number;
    /**
     * Required with accountingRule=2 (cash based)
     */
    shareEquityId?: number;
    /**
     * Required with accountingRule=2 (cash based)
     */
    shareReferenceId?: number;
    /**
     * Required with accountingRule=2 (cash based)
     */
    shareSuspenseId?: number;
    sharesIssued?: number;
    shortName?: string;
    totalShares?: number;
    unitPrice?: number;
}

