/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PostPaymentAllocation } from './postPaymentAllocation';
import { WorkingCapitalPostChargeOffReasonToExpenseAccountMappings } from './workingCapitalPostChargeOffReasonToExpenseAccountMappings';
import { WorkingCapitalLoanProductChargeToGLAccountMapper } from './workingCapitalLoanProductChargeToGLAccountMapper';
import { WorkingCapitalLoanPaymentChannelToFundSourceMappings } from './workingCapitalLoanPaymentChannelToFundSourceMappings';
import { PostAllowAttributeOverrides } from './postAllowAttributeOverrides';
import { WorkingCapitalPostWriteOffReasonToExpenseAccountMappings } from './workingCapitalPostWriteOffReasonToExpenseAccountMappings';


/**
 * PostWorkingCapitalLoanProductsRequest
 */
export interface PostWorkingCapitalLoanProductsRequest { 
    /**
     * NONE or ACC_DEF_REV_AM
     */
    accountingRule?: PostWorkingCapitalLoanProductsRequest.AccountingRuleEnum;
    allowAttributeOverrides?: PostAllowAttributeOverrides;
    amortizationType?: PostWorkingCapitalLoanProductsRequest.AmortizationTypeEnum;
    /**
     * Annual EIR percentage (6 decimal places max). Required when strategy is ANNUAL_EIR.
     */
    annualEir?: number;
    /**
     * Number of days to shift the start of the first breach schedule period after disbursement
     */
    breachGraceDays?: number;
    breachId?: number;
    /**
     * Breach start type: LOAN_CREATION or DISBURSEMENT
     */
    breachStartType?: string;
    chargeOffExpenseAccountId?: number;
    chargeOffFraudExpenseAccountId?: number;
    chargeOffReasonToExpenseAccountMappings?: Array<WorkingCapitalPostChargeOffReasonToExpenseAccountMappings>;
    closeDate?: string;
    currencyCode?: string;
    dateFormat?: string;
    deferredIncomeLiabilityAccountId?: number;
    delinquencyBucketId?: number;
    delinquencyGraceDays?: number;
    /**
     * Delinquency start type: LOAN_CREATION or DISBURSEMENT
     */
    delinquencyStartType?: string;
    description?: string;
    digitsAfterDecimal?: number;
    discount?: number;
    externalId?: string;
    feeToIncomeAccountMappings?: Array<WorkingCapitalLoanProductChargeToGLAccountMapper>;
    fundId?: number;
    fundSourceAccountId?: number;
    goodwillCreditAccountId?: number;
    inMultiplesOf?: number;
    incomeFromChargeOffFeesAccountId?: number;
    incomeFromChargeOffPenaltyAccountId?: number;
    incomeFromDiscountFeeAccountId?: number;
    incomeFromFeeAccountId?: number;
    incomeFromGoodwillCreditFeesAccountId?: number;
    incomeFromGoodwillCreditPenaltyAccountId?: number;
    incomeFromPenaltyAccountId?: number;
    incomeFromRecoveryAccountId?: number;
    loanPortfolioAccountId?: number;
    locale?: string;
    /**
     * Maximum annual EIR percentage. Optional; only for ANNUAL_EIR strategy.
     */
    maxAnnualEir?: number;
    /**
     * Maximum daily payment amount. Optional; only for PAYMENT_AMOUNT strategy.
     */
    maxPaymentAmount?: number;
    maxPeriodPaymentRate?: number;
    maxPrincipal?: number;
    /**
     * Minimum annual EIR percentage. Optional; only for ANNUAL_EIR strategy.
     */
    minAnnualEir?: number;
    /**
     * Minimum daily payment amount. Optional; only for PAYMENT_AMOUNT strategy.
     */
    minPaymentAmount?: number;
    minPeriodPaymentRate?: number;
    minPrincipal?: number;
    name?: string;
    nearBreachId?: number;
    npvDayCount?: number;
    overpaymentLiabilityAccountId?: number;
    paymentAllocation?: Array<PostPaymentAllocation>;
    /**
     * Daily payment amount, at most the currency\'s decimal precision. Required when strategy is PAYMENT_AMOUNT.
     */
    paymentAmount?: number;
    /**
     * Payment amount calculation strategy: TPV (default), ANNUAL_EIR or PAYMENT_AMOUNT
     */
    paymentAmountCalculationStrategy?: PostWorkingCapitalLoanProductsRequest.PaymentAmountCalculationStrategyEnum;
    paymentChannelToFundSourceMappings?: Array<WorkingCapitalLoanPaymentChannelToFundSourceMappings>;
    penaltyToIncomeAccountMappings?: Array<WorkingCapitalLoanProductChargeToGLAccountMapper>;
    periodPaymentRate?: number;
    principal?: number;
    receivableFeeAccountId?: number;
    receivablePenaltyAccountId?: number;
    repaymentEvery?: number;
    repaymentFrequencyType?: PostWorkingCapitalLoanProductsRequest.RepaymentFrequencyTypeEnum;
    shortName?: string;
    startDate?: string;
    transfersInSuspenseAccountId?: number;
    writeOffAccountId?: number;
    writeOffReasonsToExpenseMappings?: Array<WorkingCapitalPostWriteOffReasonToExpenseAccountMappings>;
}
export namespace PostWorkingCapitalLoanProductsRequest {
    export const AccountingRuleEnum = {
        None: 'NONE',
        AccDefRevAm: 'ACC_DEF_REV_AM'
    } as const;
    export type AccountingRuleEnum = typeof AccountingRuleEnum[keyof typeof AccountingRuleEnum];
    export const AmortizationTypeEnum = {
        Eir: 'EIR',
        Flat: 'FLAT'
    } as const;
    export type AmortizationTypeEnum = typeof AmortizationTypeEnum[keyof typeof AmortizationTypeEnum];
    export const PaymentAmountCalculationStrategyEnum = {
        Tpv: 'TPV',
        AnnualEir: 'ANNUAL_EIR',
        PaymentAmount: 'PAYMENT_AMOUNT'
    } as const;
    export type PaymentAmountCalculationStrategyEnum = typeof PaymentAmountCalculationStrategyEnum[keyof typeof PaymentAmountCalculationStrategyEnum];
    export const RepaymentFrequencyTypeEnum = {
        Days: 'DAYS',
        Months: 'MONTHS',
        Years: 'YEARS'
    } as const;
    export type RepaymentFrequencyTypeEnum = typeof RepaymentFrequencyTypeEnum[keyof typeof RepaymentFrequencyTypeEnum];
}


