/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PostWorkingCapitalLoansDataTable } from './postWorkingCapitalLoansDataTable';
import { PostPaymentAllocationRule } from './postPaymentAllocationRule';
import { PostWorkingCapitalLoansOriginatorData } from './postWorkingCapitalLoansOriginatorData';


/**
 * PostWorkingCapitalLoansRequest
 */
export interface PostWorkingCapitalLoansRequest { 
    accountNo?: string;
    /**
     * Annual EIR percentage (6 decimal places max). Required for ANNUAL_EIR strategy products.
     */
    annualEir?: number;
    /**
     * Number of days to shift the start of the first breach schedule period after disbursement
     */
    breachGraceDays?: number;
    breachId?: number;
    /**
     * Breach start type: LOAN_CREATION or DISBURSEMENT
     */
    breachStartType?: string;
    clientId: number;
    datatables?: Array<PostWorkingCapitalLoansDataTable>;
    dateFormat?: string;
    delinquencyBucketId?: number;
    delinquencyGraceDays?: number;
    /**
     * Delinquency start type: LOAN_CREATION or DISBURSEMENT
     */
    delinquencyStartType?: string;
    discount?: number;
    expectedDisbursementDate?: string;
    externalId?: string;
    fundId?: number;
    locale?: string;
    nearBreachId?: number;
    /**
     * Optional array of originators to associate with this loan. Each entry can reference an existing originator by \'id\' or \'externalId\'. If the global config \'enable_originator_creation_during_loan_application\' is enabled, non-existing originators will be auto-created using the provided details (name, typeId, channelTypeId).
     */
    originators?: Array<PostWorkingCapitalLoansOriginatorData>;
    paymentAllocation?: Array<PostPaymentAllocationRule>;
    /**
     * Daily payment amount, at most the currency\'s decimal precision. Overrides the product default on PAYMENT_AMOUNT strategy products.
     */
    paymentAmount?: number;
    periodPaymentRate?: number;
    /**
     * Principal (disbursement) amount
     */
    principalAmount: number;
    productId: number;
    repaymentEvery?: number;
    repaymentFrequencyType?: PostWorkingCapitalLoansRequest.RepaymentFrequencyTypeEnum;
    submittedOnDate?: string;
    submittedOnNote?: string;
    totalPaymentVolume?: number;
}
export namespace PostWorkingCapitalLoansRequest {
    export const RepaymentFrequencyTypeEnum = {
        Days: 'DAYS',
        Months: 'MONTHS',
        Years: 'YEARS'
    } as const;
    export type RepaymentFrequencyTypeEnum = typeof RepaymentFrequencyTypeEnum[keyof typeof RepaymentFrequencyTypeEnum];
}


