/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PostWorkingCapitalLoanTransactionsPaymentDetailRequest } from './postWorkingCapitalLoanTransactionsPaymentDetailRequest';


/**
 * Request for transaction command: repayment, creditBalanceRefund, discountFee, discountFeeAdjustment, chargeOff, undoChargeOff, writeOff or undoWriteOff
 */
export interface PostWorkingCapitalLoanTransactionsRequest { 
    /**
     * Optional charge-off reason code value id (command=chargeOff)
     */
    chargeOffReasonId?: number;
    /**
     * Optional code value id for transaction classification
     */
    classificationId?: number;
    dateFormat?: string;
    externalId?: string;
    locale?: string;
    note?: string;
    paymentDetails?: PostWorkingCapitalLoanTransactionsPaymentDetailRequest;
    /**
     * Disbursement transaction id for discountFee; discount fee transaction id for discountFeeAdjustment
     */
    relatedResourceId?: number;
    /**
     * Optional external id for the reversal (command=undoChargeOff, undoWriteOff)
     */
    reversalExternalId?: string;
    /**
     * Transaction amount. For command=recoveryPayment it may not exceed the loan\'s writtenOffOutstanding
     */
    transactionAmount?: number;
    /**
     * Transaction date
     */
    transactionDate?: string;
    /**
     * Optional write-off reason code value id (command=writeOff)
     */
    writeoffReasonId?: number;
}

