/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * PutSavingsProductsProductIdRequest
 */
export interface PutSavingsProductsProductIdRequest { 
    accountingRule?: number;
    allowOverdraft?: boolean;
    currencyCode?: string;
    description?: string;
    digitsAfterDecimal?: number;
    enforceMinRequiredBalance?: boolean;
    feesReceivableAccountId?: number;
    inMultiplesOf?: number;
    incomeFromFeeAccountId?: number;
    incomeFromInterestId?: number;
    incomeFromPenaltyAccountId?: number;
    interestCalculationDaysInYearType?: number;
    interestCalculationType?: number;
    interestCompoundingPeriodType?: number;
    interestOnSavingsAccountId?: number;
    interestPayableAccountId?: number;
    interestPostingPeriodType?: number;
    interestRate?: number;
    interestReceivableAccountId?: number;
    locale?: string;
    minRequiredOpeningBalance?: number;
    name?: string;
    nominalAnnualInterestRate?: number;
    nominalAnnualInterestRateOverdraft?: number;
    overdraftLimit?: number;
    overdraftPortfolioControlId?: number;
    penaltiesReceivableAccountId?: number;
    savingsControlAccountId?: number;
    savingsReferenceAccountId?: number;
    shortName?: string;
    transfersInSuspenseAccountId?: number;
    withHoldTax?: boolean;
    withdrawalFeeForTransfers?: boolean;
    writeOffAccountId?: number;
}

