/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PostPaymentAllocationRule } from './postPaymentAllocationRule';


/**
 * PutWorkingCapitalLoansLoanIdRequest
 */
export interface PutWorkingCapitalLoansLoanIdRequest { 
    accountNo?: string;
    /**
     * Number of days to shift the start of the first breach schedule period after disbursement
     */
    breachGraceDays?: number;
    breachId?: number;
    /**
     * Breach start type: LOAN_CREATION or DISBURSEMENT
     */
    breachStartType?: string;
    clientId?: number;
    dateFormat?: string;
    delinquencyBucketId?: number;
    delinquencyGraceDays?: number;
    /**
     * Delinquency start type: LOAN_CREATION or DISBURSEMENT
     */
    delinquencyStartType?: string;
    discount?: number;
    expectedDisbursementDate?: string;
    externalId?: string;
    fundId?: number;
    locale?: string;
    nearBreachId?: number;
    paymentAllocation?: Array<PostPaymentAllocationRule>;
    /**
     * Daily payment amount, at most the currency\'s decimal precision. Overrides the product default on PAYMENT_AMOUNT strategy products.
     */
    paymentAmount?: number;
    periodPaymentRate?: number;
    /**
     * Principal (disbursement) amount
     */
    principalAmount?: number;
    productId?: number;
    repaymentEvery?: number;
    repaymentFrequencyType?: PutWorkingCapitalLoansLoanIdRequest.RepaymentFrequencyTypeEnum;
    submittedOnDate?: string;
    /**
     * Max length 500 characters
     */
    submittedOnNote?: string;
    totalPaymentVolume?: number;
}
export namespace PutWorkingCapitalLoansLoanIdRequest {
    export const RepaymentFrequencyTypeEnum = {
        Days: 'DAYS',
        Months: 'MONTHS',
        Years: 'YEARS'
    } as const;
    export type RepaymentFrequencyTypeEnum = typeof RepaymentFrequencyTypeEnum[keyof typeof RepaymentFrequencyTypeEnum];
}


