/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkingCapitalCollectionDelinquencyPausePeriod } from './workingCapitalCollectionDelinquencyPausePeriod';
import { WorkingCapitalCollectionRangeScheduleDelinquency } from './workingCapitalCollectionRangeScheduleDelinquency';


/**
 * Working Capital Delinquency Collection Data
 */
export interface WorkingCapitalCollection { 
    /**
     * Pause periods during which delinquency is not counted
     */
    delinquencyPausePeriods?: Array<WorkingCapitalCollectionDelinquencyPausePeriod>;
    /**
     * Total delinquent amount
     */
    delinquentAmount?: number;
    /**
     * Date when the loan became delinquent
     */
    delinquentDate?: string;
    /**
     * Number of days the loan has been delinquent, from the oldest active delinquency tag
     */
    delinquentDays?: number;
    /**
     * Delinquent principal amount
     */
    delinquentPrincipal?: number;
    /**
     * Delinquency amounts grouped by age range (installment-level delinquency; Term-compatible name)
     */
    installmentLevelDelinquency?: Array<WorkingCapitalCollectionRangeScheduleDelinquency>;
    /**
     * Amount of the last payment made on the loan
     */
    lastPaymentAmount?: number;
    /**
     * Date the loan was last paid by any repayment like transaction (repayment, goodwill credit, payout refund or charge adjustment)
     */
    lastPaymentDate?: string;
    /**
     * Amount of the last repayment made on the loan
     */
    lastRepaymentAmount?: number;
    /**
     * Date the loan was last repaid by a repayment transaction
     */
    lastRepaymentDate?: string;
    /**
     * Days the oldest unmet minimum-payment period is past due (measured from its toDate); 0 when not past due
     */
    pastDueDays?: number;
}

