/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentTypeData } from './paymentTypeData';
import { CurrencyData } from './currencyData';
import { CodeValueData } from './codeValueData';
import { LoanTransactionEnumData } from './loanTransactionEnumData';


/**
 * Transaction template for one command. Every command fills expectedAmount; the remaining fields are the extras that only some commands carry, and are left null otherwise. Amounts that come from what is owed are reported as of the requested transactionDate; amounts that come from what has been paid, written off or recovered do not vary with it.
 */
export interface WorkingCapitalLoanTransactionTemplateResponse { 
    /**
     * chargeOff only: defaults to the business date
     */
    chargeOffDate?: string;
    /**
     * chargeOff only: charge-off reason options
     */
    chargeOffReasonOptions?: Array<CodeValueData>;
    /**
     * Classification options for the command\'s classification code
     */
    classificationOptions?: Array<CodeValueData>;
    currency?: CurrencyData;
    /**
     * disburse only: approved discount amount
     */
    discountAmount?: number;
    /**
     * Suggested amount to pre-fill, which the user may change. Its meaning follows the requested command: outstanding principal for repayment and goodwillCredit, the overpayment for creditBalanceRefund, the still-recoverable amount for recoveryPayment, the approved principal for disburse, the full payoff for prepayLoan, and the outstanding balance for chargeOff
     */
    expectedAmount?: number;
    /**
     * disburse only: expected disbursement date
     */
    expectedDisbursementDate?: string;
    /**
     * prepayLoan only: outstanding fee portion of the payoff amount
     */
    feeChargesPortion?: number;
    /**
     * disburse only: whether the product forbids overriding the default discount
     */
    overrideDiscountDisabled?: boolean;
    /**
     * Payment type options, where the command records a payment
     */
    paymentTypeOptions?: Array<PaymentTypeData>;
    /**
     * prepayLoan only: outstanding penalty portion of the payoff amount
     */
    penaltyChargesPortion?: number;
    /**
     * prepayLoan only: outstanding principal portion of the payoff amount
     */
    principalPortion?: number;
    transactionDate?: string;
    type?: LoanTransactionEnumData;
    wcLoanId?: number;
}

